version: "3.9"
services:
  reader:
    image: "yadariya/tvlab:latest-task4"
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - HOST=rabbit
      - PORT=5672
      - USER=test
      - PASSWORD=test
    deploy:
      replicas: 3

  sender:
    image: "yadariya/tvlab:latest-task4"
    restart: unless-stopped
    command: python -u sender.py
    environment:
      - HOST=rabbit
      - PORT=5672
      - USER=test
      - PASSWORD=test

  rabbit:
    image: "rabbitmq:3.11-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
